version: '3'
services:
  db:
    image: mysql
    command: mysqld --default-authentication-plugin=mysql_native_password
    volumes: 
      - sample-app-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
  app:
    build:
      context: .
      dockerfile: docker/ruby/Dockerfile
    command: docker/ruby/entrypoint.sh
    volumes:
      - .:/myapp
    env_file: .env
    ports:
      - "3000:3000"
volumes: 
  sample-app-db: